[phases.setup]
nixPkgs = ["php82", "php82Extensions.intl", "php82Extensions.mbstring", "php82Extensions.mysqlnd", "php82Extensions.curl", "php82Extensions.pdo", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-intl"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"